name: NACdesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09aded'
    - '#f8f6d8'
    - '#f85751'
    - '#0b031e'
    - '#d6021e'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
