name: NACdesign
favicon: null
layout_spectrum: 0.24832
typography_spectrum: 0.0919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09aded'
    - '#f8f6d8'
    - '#f85751'
    - '#0b031e'
    - '#d6021e'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
